### PR TITLE
Sidebar added and SignOut button functional

### PR DESCRIPTION
**Pull request by trstnb1998**
Sidebar started with minimal functionality(it works but still in progress). SignOut button working

### CODE REVIEW

**Comment by robinsonlam** [comment]
Build failed

Click on "Details" to see the error and fix it - commit and push and see if it rebuilds properly.

@trstnb1998

**Review by robinsonlam — COMMENTED** [review]
Changes look great! Great work

**Comment by robinsonlam** [comment]
LOL all good

**Review by robinsonlam — APPROVED** [review]

**Comment by trstnb1998** [comment]
Sidebar added and working sign out button / lines deleted in App.jsx to fix potential cause of build errors

**Pull request merged**
